inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.1
  DisplayCopNames: true
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/**/*'
    - 'script/**/*'
    - 'spec/test_app_templates/**/*'
    - 'vendor/**/*'

Lint/ImplicitStringConcatenation:
  Exclude:
    - 'hydra-core/lib/generators/**/*'

Metrics/LineLength:
  Max: 400

Metrics/AbcSize:
  Max: 30
  Exclude:

Metrics/MethodLength:
  Max: 15

Style/SymbolProc: # https://github.com/bbatsov/rubocop/issues/3071
  Exclude:

Style/IndentationConsistency:
  EnforcedStyle: rails

Style/CollectionMethods:
  PreferredMethods:
    collect: 'map'
    collect!: 'map!'
    inject: 'reduce'
    detect: 'find'
    find_all: 'select'

Style/WordArray:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false

Style/FileName:
  Exclude:
    - 'hydra-core/lib/hydra-core.rb'

Rails:
  Enabled: true

Rails/OutputSafety:
  Exclude:

RSpec/DescribeClass:
  Exclude:
    - 'hydra-core/spec/controllers/ip_based_ability_spec.rb'

RSpec/ExpectActual:
  Enabled: false

RSpec/FilePath:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

RSpec/MessageExpectation:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/LeadingSubject:
  Enabled: false
